superset:
  image:
    repository: apache/superset
    tag: latest
    pullPolicy: Always
  init:
    adminUser:
      username: admin
      firstname: Superset
      lastname: Admin
      email: admin@superset.com
      password: admin
  bootstrapScript: |
    #!/bin/bash
    rm -rf /var/lib/apt/lists/* && \
    pip install \
      psycopg2-binary==2.9.1 \
      sqlalchemy-trino==0.4.1 \
      redis==3.5.3 && \
    if [ ! -f ~/bootstrap ]; then echo "Running Superset with uid {{ .Values.runAsUser }}" > ~/bootstrap; fi
  extraConfigs:
    import_datasources.yaml: |
      databases:
      {{ include "superset.discovery" . }}
  discovery:
    hive: true
    mongodb: true
    postgres: true
    elastic: true




ingress:
  enabled: true
  tls: true
  annotations:
    kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hostname: chart-example.local
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local



